apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: handwriting-recognition
build:
  artifacts:
    - image: handwriting-recognition
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  custom:
    command: "docker-compose up --build"