apiVersion: skaffold/v4beta5  # 确保使用您的 Skaffold 版本对应的正确 apiVersion
kind: Config
metadata:
  name: handwriting-recognition
build:
  artifacts:
    - image: handwriting-recognition
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  docker:
    images: [handwriting-recognition]
